const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const vm = require('vm');
const { spawnSync } = require('child_process');
const { transpileMulda, compileMulda } = require('../compiler/src/transpile');
const { runBytecodeObject } = require('../runtime/src/vm');
const { parseArgs } = require('../runtime/src/run');
const { parseCommandArgs, resolveCToolchain, writeNativeArtifactMetadata } = require('../runtime/src/mulda');

function testVariablesAndPrint() {
  const source = [
    '# test',
    'Hokna',
    'dej x = 40 + 2',
    'vyblij "Ahoj"',
    'vyblij x'
  ].join('\n');

  const js = transpileMulda(source);
  assert(js.includes('const __muldaTrace ='));
  assert(js.includes('let x = (40 + 2);'));
  assert(js.includes('console.log("Ahoj");'));
  assert(js.includes('console.log(x);'));
}

function testAssignmentStatementParsingAndTranspile() {
  const source = [
    'Hokna',
    'dej x = 1',
    'x = x + 2',
    'vyblij x'
  ].join('\n');

  const { ast, js, bytecode } = compileMulda(source);
  assert.deepStrictEqual(ast[1], { type: 'assign', name: 'x', expr: 'x + 2', line: 3 });
  assert(js.includes('x = (x + 2);'));
  assert(js.includes('op: "ASSIGN"'));
  assert(bytecode.instructions.some((ins) => ins.op === 'ASSIGN' && ins.name === 'x' && ins.expr === 'x + 2'));
}

function testControlFlowBlocks() {
  const source = [
    'Hokna',
    'dej x = 2',
    'opakuj 3',
    '  dyz x > 0',
    '    vyblij x',
    '  konec',
    'konec'
  ].join('\n');

  const js = transpileMulda(source);
  assert(js.includes('for (let __mulda_i1 = 0; __mulda_i1 < (3); __mulda_i1 += 1) {'));
  assert(js.includes('if ((x > 0)) {'));
  assert(js.includes('console.log(x);'));
}

function testBooleanTokensAndTypeAnnotation() {
  const source = [
    'Hokna',
    'dej jeTo: joNeboHovno = jo',
    'dyz jeTo aKurva nechcu hovno',
    '  vyblij jeTo bo hovno',
    'konec'
  ].join('\n');

  const js = transpileMulda(source);
  assert(js.includes('let jeTo = (true);'));
  assert(js.includes('if ((jeTo && ! false)) {'));
  assert(js.includes('console.log(jeTo || false);'));
}

function testFunctionDeclarationAndReturn() {
  const source = [
    'Hokna',
    'funkcicka secti(a, b)',
    '  dej sum = a + b',
    '  dyz sum > 0',
    '    vrat sum',
    '  konec',
    '  vrat 0',
    'konec'
  ].join('\n');

  const js = transpileMulda(source);
  assert(js.includes('// generated by mulda transpiler v0.9.0'));
  assert(js.includes('function secti(a, b) {'));
}

function testDeprecatedAliasesStillWork() {
  const source = [
    'nacpi',
    'funkce secti(a, b)',
    '  kdyz a > 0',
    '    vrat a + b',
    '  konec',
    '  vrat b',
    'konec',
    'rekni Nazdar',
    'spocitej secti(1, 1)'
  ].join('\n');
  const js = transpileMulda(source);
  assert(js.includes('function secti(a, b) {'));
  assert(js.includes('if ((a > 0)) {'));
  assert(js.includes('console.log("Nazdar");'));
  assert(js.includes('console.log(secti(1, 1));'));
}


function testStartKeywordRequiredAndUnique() {
  assert.throws(() => transpileMulda('vyblij 1'), /Program must start with "Hokna"/);
  assert.throws(() => transpileMulda(['Hokna', 'vyblij 1', 'Hokna'].join('\n')), /allowed only once/);
  assert.throws(() => transpileMulda(['dej x = 1', 'Hokna'].join('\n')), /Program must start with "Hokna"/);
}

function testUnexpectedKonecError() {
  assert.throws(() => transpileMulda(['Hokna', 'konec'].join('\n')), /Unexpected "konec"/);
}

function testAssignmentValidationErrors() {
  assert.throws(() => transpileMulda(['Hokna', '123 = 1'].join('\n')), /Unsupported syntax/);
  assert.throws(() => transpileMulda(['Hokna', 'x = '].join('\n')), /Assignment requires expression after "="/);
}

function testEqualityExpressionsAreNotParsedAsAssignments() {
  const printJs = transpileMulda(['Hokna', 'vyblij 1 == 1'].join('\n'));
  assert(printJs.includes('console.log(1 == 1);'));

  const fnJs = transpileMulda([
    'Hokna',
    'funkcicka jeStejne(a, b)',
    '  vrat a == b',
    'konec',
    'vyblij jeStejne(1, 1)'
  ].join('\n'));
  assert(fnJs.includes('return (a == b);'));

  assert.throws(() => transpileMulda(['Hokna', 'x == 1'].join('\n')), /Unsupported syntax/);
}

function testBytecodeVmRunner() {
  const source = [
    'Hokna',
    'funkcicka secti(a, b)',
    '  vrat a + b',
    'konec',
    'dej n = 2',
    'n = n + 1',
    'opakuj 2',
    '  dyz n > 0',
    '    vyblij secti(n, 3)',
    '  konec',
    'konec',
    'vyblij obsahuje("mulda", "ul")'
  ].join('\n');

  const { bytecode } = compileMulda(source);
  assert.strictEqual(bytecode.version, '0.9.0');
  assert.strictEqual(bytecode.target, 'mulda-vm');

  const lines = [];
  runBytecodeObject(bytecode, { stdout: (line) => lines.push(String(line)) });
  assert.deepStrictEqual(lines, ['6', '6', 'true']);
}

function testRuntimeArgParsers() {
  const runtimeParsed = parseArgs(['--trace', 'dist/demo.bytecode.json']);
  assert.strictEqual(runtimeParsed.options.trace, true);
  assert.deepStrictEqual(runtimeParsed.positional, ['dist/demo.bytecode.json']);

  const muldaParsed = parseCommandArgs(['--debug', 'examples/hello.mulda']);
  assert.strictEqual(muldaParsed.options.trace, true);
  assert.strictEqual(muldaParsed.inputFile, 'examples/hello.mulda');

  const runtimeJson = parseArgs(['--trace-json', 'dist/demo.js']);
  assert.strictEqual(runtimeJson.options.trace, true);
  assert.strictEqual(runtimeJson.options.traceFormat, 'json');

  const muldaJson = parseCommandArgs(['--trace-json', '--bc', 'examples/hello.mulda']);
  assert.strictEqual(muldaJson.options.trace, true);
  assert.strictEqual(muldaJson.options.traceFormat, 'json');
  assert.strictEqual(muldaJson.options.bytecode, true);
}

function testTraceEventsPresentInBothBackends() {
  const source = ['Hokna', 'dej x = 1', 'x = x + 1', 'vyblij x'].join('\n');
  const { js, bytecode } = compileMulda(source);

  const jsTrace = [];
  vm.runInNewContext(js, {
    __muldaTraceHook: (event) => jsTrace.push(event),
    console: { log: () => {} }
  });
  assert(jsTrace.some((event) => event.op === 'DECLARE'));
  assert(jsTrace.some((event) => event.op === 'ASSIGN'));
  assert(jsTrace.some((event) => event.op === 'PRINT_EXPR'));
  assert(jsTrace.some((event) => event.op === 'DECLARE' && event.detail === 'x=1'));
  assert(jsTrace.some((event) => event.op === 'ASSIGN' && event.detail === 'x=2'));

  const vmTrace = [];
  runBytecodeObject(bytecode, {
    stdout: () => {},
    trace: (event) => vmTrace.push(event)
  });
  assert(vmTrace.some((event) => event.op === 'DECLARE'));
  assert(vmTrace.some((event) => event.op === 'ASSIGN'));
  assert(vmTrace.some((event) => event.op === 'PRINT_EXPR'));
  assert(vmTrace.some((event) => event.op === 'DECLARE' && event.detail === 'x=1'));
  assert(vmTrace.some((event) => event.op === 'ASSIGN' && event.detail === 'x=2'));
}

function testAssignUnknownVariableThrowsInVm() {
  const { bytecode } = compileMulda(['Hokna', 'x = 1'].join('\n'));
  assert.throws(
    () => runBytecodeObject(bytecode, { stdout: () => {} }),
    /Assignment failed: variable "x" is not declared/
  );
}

function testCBackendGenerationAndArgs() {
  const source = [
    'Hokna',
    'dej x = 1',
    'x = x + 2',
    'dyz x > 2',
    '  vyblij x',
    'konec'
  ].join('\n');
  const { c } = compileMulda(source);
  assert(c.includes('generated by mulda transpiler v0.9.0'));
  assert(c.includes('__mulda_trace_num_var("DECLARE"') || c.includes('__mulda_trace_bool_var("DECLARE"'));
  assert(c.includes('__mulda_trace_num_var("ASSIGN"'));
  assert(c.includes('if ((x > 2)) {'));

  const parsedCompile = parseCommandArgs(['--target', 'c', '--platform', 'windows-x64', 'examples/hello.mulda']);
  assert.strictEqual(parsedCompile.options.target, 'c');
  assert.strictEqual(parsedCompile.options.platform, 'windows-x64');

  const parsedRun = parseCommandArgs(['--c', '--trace-json', 'examples/hello.mulda']);
  assert.strictEqual(parsedRun.options.cBackend, true);
  assert.strictEqual(parsedRun.options.traceFormat, 'json');

  assert.deepStrictEqual(resolveCToolchain('linux-x64'), { cc: 'gcc', outputExt: '', targetLabel: 'linux-x64' });
  assert.deepStrictEqual(resolveCToolchain('windows-x64'), { cc: 'x86_64-w64-mingw32-gcc', outputExt: '.exe', targetLabel: 'windows-x64' });
  assert.strictEqual(resolveCToolchain('darwin-arm64'), null);
}

function testCBackendCallArgumentSplitHandlesEscapedQuoteAndComma() {
  const source = [
    'Hokna',
    'vyblij obsahuje("a\\\",b", "b")'
  ].join('\n');

  const { c } = compileMulda(source);
  assert(c.includes('__mulda_obsahuje("a\\\",b", "b")'));
}

function testCBackendBoolAssignmentUsesBoolTrace() {
  const source = [
    'Hokna',
    'dej flag: joNeboHovno = jo',
    'flag = hovno',
    'vyblij flag'
  ].join('\n');

  const { c } = compileMulda(source);
  assert(c.includes('__mulda_trace_bool_var("DECLARE", 2, "flag", flag);'));
  assert(c.includes('__mulda_trace_bool_var("ASSIGN", 3, "flag", flag);'));
}

function testNativeArtifactMetadataSidecar() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mulda-meta-'));
  const artifactPath = path.join(tmpDir, 'hello-linux-x64');

  writeNativeArtifactMetadata({
    sourceFile: '/workspace/examples/hello.mulda',
    cFile: '/workspace/dist/hello.c',
    artifactFile: artifactPath,
    toolchain: { cc: 'gcc', outputExt: '', targetLabel: 'linux-x64' },
    platform: 'linux-x64'
  });

  const metadataPath = `${artifactPath}.metadata.json`;
  assert.strictEqual(fs.existsSync(metadataPath), true);

  const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  assert.strictEqual(metadata.lang, 'mulda');
  assert.strictEqual(metadata.backend, 'c');
  assert.strictEqual(metadata.platform, 'linux-x64');
  assert.strictEqual(metadata.compiler, 'gcc');
  assert.strictEqual(metadata.artifactFile, artifactPath);
  assert.strictEqual(typeof metadata.version, 'string');
  assert.strictEqual(typeof metadata.generatedAt, 'string');
}

function testCrossBuildManifestScript() {
  const projectRoot = path.resolve(__dirname, '..');
  const script = path.join(projectRoot, 'scripts/build-cross-c.js');
  const source = path.join(projectRoot, 'examples/hello.mulda');
  const run = spawnSync(process.execPath, [script, source], {
    cwd: projectRoot,
    encoding: 'utf8'
  });

  const runFromElsewhere = spawnSync(process.execPath, [script, 'examples/hello.mulda'], {
    cwd: os.tmpdir(),
    encoding: 'utf8'
  });

  const manifestPath = path.join(projectRoot, 'dist/hello.release-manifest.json');
  assert.strictEqual(fs.existsSync(manifestPath), true);
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  assert.strictEqual(manifest.lang, 'mulda');
  assert.strictEqual(manifest.version, '1.0.0-rc.2');
  assert.strictEqual(typeof manifest.cSource, 'string');
  assert.strictEqual(typeof manifest.cSourceSha256, 'string');
  assert.strictEqual(manifest.cSourceSha256.length, 64);
  assert(manifest.platforms['linux-x64']);
  assert(manifest.platforms['windows-x64']);
  assert(['ok', 'failed'].includes(manifest.platforms['linux-x64'].status));
  assert(['ok', 'failed'].includes(manifest.platforms['windows-x64'].status));

  // Script returns non-zero when some toolchain is unavailable (expected in many local envs).
  assert([0, 2].includes(run.status || 0));
  assert([0, 2].includes(runFromElsewhere.status || 0));
}

function testCTraceSnapshotsWhenGccAvailable() {
  const gcc = spawnSync('gcc', ['--version'], { stdio: 'ignore' });
  if (gcc.status !== 0) {
    console.log('skip c trace snapshot e2e (gcc unavailable)');
    return;
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mulda-c-trace-'));
  const cPath = path.join(tmpDir, 'demo.c');
  const binPath = path.join(tmpDir, 'demo.bin');

  const { c } = compileMulda(['Hokna', 'dej x = 2', 'x = x + 3', 'vyblij x'].join('\n'));
  fs.writeFileSync(cPath, c, 'utf8');

  const cc = spawnSync('gcc', [cPath, '-std=c11', '-O2', '-o', binPath], { stdio: 'inherit' });
  assert.strictEqual(cc.status || 0, 0, 'gcc compile should pass (trace snapshot)');

  const run = spawnSync(binPath, {
    encoding: 'utf8',
    env: {
      ...process.env,
      MULDA_TRACE: '1',
      MULDA_TRACE_FORMAT: 'json'
    }
  });
  assert.strictEqual(run.status || 0, 0, 'c binary should run (trace snapshot)');

  const events = (run.stderr || '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => JSON.parse(line));

  assert(events.some((event) => event.op === 'DECLARE' && event.detail === 'x=2'));
  assert(events.some((event) => event.op === 'ASSIGN' && event.detail === 'x=5'));

  const snapshots = events.filter((event) => event.op === 'SNAPSHOT' && /^x=/.test(event.detail || ''));
  assert.deepStrictEqual(snapshots.map((event) => event.detail), ['x=2', 'x=5']);
}

function testCBoolTraceSnapshotsWhenGccAvailable() {
  const gcc = spawnSync('gcc', ['--version'], { stdio: 'ignore' });
  if (gcc.status !== 0) {
    console.log('skip c bool trace snapshot e2e (gcc unavailable)');
    return;
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mulda-c-bool-trace-'));
  const cPath = path.join(tmpDir, 'demo.c');
  const binPath = path.join(tmpDir, 'demo.bin');

  const { c } = compileMulda(['Hokna', 'dej flag: joNeboHovno = jo', 'flag = hovno', 'vyblij flag'].join('\n'));
  fs.writeFileSync(cPath, c, 'utf8');

  const cc = spawnSync('gcc', [cPath, '-std=c11', '-O2', '-o', binPath], { stdio: 'inherit' });
  assert.strictEqual(cc.status || 0, 0, 'gcc compile should pass (bool trace snapshot)');

  const run = spawnSync(binPath, {
    encoding: 'utf8',
    env: {
      ...process.env,
      MULDA_TRACE: '1',
      MULDA_TRACE_FORMAT: 'json'
    }
  });
  assert.strictEqual(run.status || 0, 0, 'c binary should run (bool trace snapshot)');

  const events = (run.stderr || '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => JSON.parse(line));

  assert(events.some((event) => event.op === 'DECLARE' && event.detail === 'flag=true'));
  assert(events.some((event) => event.op === 'ASSIGN' && event.detail === 'flag=false'));

  const snapshots = events.filter((event) => event.op === 'SNAPSHOT' && /^flag=/.test(event.detail || ''));
  assert.deepStrictEqual(snapshots.map((event) => event.detail), ['flag=true', 'flag=false']);
}

function testCE2EWhenGccAvailable() {
  const gcc = spawnSync('gcc', ['--version'], { stdio: 'ignore' });
  if (gcc.status !== 0) {
    console.log('skip c e2e (gcc unavailable)');
    return;
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mulda-c-e2e-'));
  const cPath = path.join(tmpDir, 'demo.c');
  const binPath = path.join(tmpDir, 'demo.bin');

  const { c } = compileMulda(['Hokna', 'dej x = 2', 'x = x + 3', 'vyblij x'].join('\n'));
  fs.writeFileSync(cPath, c, 'utf8');

  const cc = spawnSync('gcc', [cPath, '-std=c11', '-O2', '-o', binPath], { stdio: 'inherit' });
  assert.strictEqual(cc.status || 0, 0, 'gcc compile should pass');

  const run = spawnSync(binPath, { encoding: 'utf8' });
  assert.strictEqual(run.status || 0, 0, 'c binary should run');
  assert.strictEqual((run.stdout || '').trim(), '5');
}

testVariablesAndPrint();
testAssignmentStatementParsingAndTranspile();
testControlFlowBlocks();
testBooleanTokensAndTypeAnnotation();
testFunctionDeclarationAndReturn();
testDeprecatedAliasesStillWork();
testStartKeywordRequiredAndUnique();
testUnexpectedKonecError();
testAssignmentValidationErrors();
testEqualityExpressionsAreNotParsedAsAssignments();
testBytecodeVmRunner();
testRuntimeArgParsers();
testTraceEventsPresentInBothBackends();
testAssignUnknownVariableThrowsInVm();
testCBackendGenerationAndArgs();
testCBackendCallArgumentSplitHandlesEscapedQuoteAndComma();
testCBackendBoolAssignmentUsesBoolTrace();
testNativeArtifactMetadataSidecar();
testCrossBuildManifestScript();
testCTraceSnapshotsWhenGccAvailable();
testCBoolTraceSnapshotsWhenGccAvailable();
testCE2EWhenGccAvailable();
console.log('tests passed');
