const assert = require('assert');
const vm = require('vm');
const { transpileMulda, compileMulda } = require('../compiler/src/transpile');
const { runBytecodeObject } = require('../runtime/src/vm');
const { parseArgs } = require('../runtime/src/run');
const { parseCommandArgs } = require('../runtime/src/mulda');

function testVariablesAndPrint() {
  const source = [
    '# test',
    'Hokna',
    'dej x = 40 + 2',
    'vyblij "Ahoj"',
    'vyblij x'
  ].join('\n');

  const js = transpileMulda(source);
  assert(js.includes('const __muldaTrace ='));
  assert(js.includes('let x = (40 + 2);'));
  assert(js.includes('console.log("Ahoj");'));
  assert(js.includes('console.log(x);'));
}

function testAssignmentStatementParsingAndTranspile() {
  const source = [
    'Hokna',
    'dej x = 1',
    'x = x + 2',
    'vyblij x'
  ].join('\n');

  const { ast, js, bytecode } = compileMulda(source);
  assert.deepStrictEqual(ast[1], { type: 'assign', name: 'x', expr: 'x + 2', line: 3 });
  assert(js.includes('x = (x + 2);'));
  assert(js.includes('op: "ASSIGN"'));
  assert(bytecode.instructions.some((ins) => ins.op === 'ASSIGN' && ins.name === 'x' && ins.expr === 'x + 2'));
}

function testControlFlowBlocks() {
  const source = [
    'Hokna',
    'dej x = 2',
    'opakuj 3',
    '  dyz x > 0',
    '    vyblij x',
    '  konec',
    'konec'
  ].join('\n');

  const js = transpileMulda(source);
  assert(js.includes('for (let __mulda_i1 = 0; __mulda_i1 < (3); __mulda_i1 += 1) {'));
  assert(js.includes('if ((x > 0)) {'));
  assert(js.includes('console.log(x);'));
}

function testBooleanTokensAndTypeAnnotation() {
  const source = [
    'Hokna',
    'dej jeTo: joNeboHovno = jo',
    'dyz jeTo aKurva nechcu hovno',
    '  vyblij jeTo bo hovno',
    'konec'
  ].join('\n');

  const js = transpileMulda(source);
  assert(js.includes('let jeTo = (true);'));
  assert(js.includes('if ((jeTo && ! false)) {'));
  assert(js.includes('console.log(jeTo || false);'));
}

function testFunctionDeclarationAndReturn() {
  const source = [
    'Hokna',
    'funkcicka secti(a, b)',
    '  dej sum = a + b',
    '  dyz sum > 0',
    '    vrat sum',
    '  konec',
    '  vrat 0',
    'konec'
  ].join('\n');

  const js = transpileMulda(source);
  assert(js.includes('// generated by mulda transpiler v0.7.3'));
  assert(js.includes('function secti(a, b) {'));
}

function testDeprecatedAliasesStillWork() {
  const source = [
    'nacpi',
    'funkce secti(a, b)',
    '  kdyz a > 0',
    '    vrat a + b',
    '  konec',
    '  vrat b',
    'konec',
    'rekni Nazdar',
    'spocitej secti(1, 1)'
  ].join('\n');
  const js = transpileMulda(source);
  assert(js.includes('function secti(a, b) {'));
  assert(js.includes('if ((a > 0)) {'));
  assert(js.includes('console.log("Nazdar");'));
  assert(js.includes('console.log(secti(1, 1));'));
}


function testStartKeywordRequiredAndUnique() {
  assert.throws(() => transpileMulda('vyblij 1'), /Program must start with "Hokna"/);
  assert.throws(() => transpileMulda(['Hokna', 'vyblij 1', 'Hokna'].join('\n')), /allowed only once/);
  assert.throws(() => transpileMulda(['dej x = 1', 'Hokna'].join('\n')), /Program must start with "Hokna"/);
}

function testUnexpectedKonecError() {
  assert.throws(() => transpileMulda(['Hokna', 'konec'].join('\n')), /Unexpected "konec"/);
}

function testAssignmentValidationErrors() {
  assert.throws(() => transpileMulda(['Hokna', '123 = 1'].join('\n')), /Unsupported syntax/);
  assert.throws(() => transpileMulda(['Hokna', 'x = '].join('\n')), /Assignment requires expression after "="/);
}

function testEqualityExpressionsAreNotParsedAsAssignments() {
  const printJs = transpileMulda(['Hokna', 'vyblij 1 == 1'].join('\n'));
  assert(printJs.includes('console.log(1 == 1);'));

  const fnJs = transpileMulda([
    'Hokna',
    'funkcicka jeStejne(a, b)',
    '  vrat a == b',
    'konec',
    'vyblij jeStejne(1, 1)'
  ].join('\n'));
  assert(fnJs.includes('return (a == b);'));

  assert.throws(() => transpileMulda(['Hokna', 'x == 1'].join('\n')), /Unsupported syntax/);
}

function testBytecodeVmRunner() {
  const source = [
    'Hokna',
    'funkcicka secti(a, b)',
    '  vrat a + b',
    'konec',
    'dej n = 2',
    'n = n + 1',
    'opakuj 2',
    '  dyz n > 0',
    '    vyblij secti(n, 3)',
    '  konec',
    'konec',
    'vyblij obsahuje("mulda", "ul")'
  ].join('\n');

  const { bytecode } = compileMulda(source);
  assert.strictEqual(bytecode.version, '0.7.3');
  assert.strictEqual(bytecode.target, 'mulda-vm');

  const lines = [];
  runBytecodeObject(bytecode, { stdout: (line) => lines.push(String(line)) });
  assert.deepStrictEqual(lines, ['6', '6', 'true']);
}

function testRuntimeArgParsers() {
  const runtimeParsed = parseArgs(['--trace', 'dist/demo.bytecode.json']);
  assert.strictEqual(runtimeParsed.options.trace, true);
  assert.deepStrictEqual(runtimeParsed.positional, ['dist/demo.bytecode.json']);

  const muldaParsed = parseCommandArgs(['--debug', 'examples/hello.mulda']);
  assert.strictEqual(muldaParsed.options.trace, true);
  assert.strictEqual(muldaParsed.inputFile, 'examples/hello.mulda');

  const runtimeJson = parseArgs(['--trace-json', 'dist/demo.js']);
  assert.strictEqual(runtimeJson.options.trace, true);
  assert.strictEqual(runtimeJson.options.traceFormat, 'json');

  const muldaJson = parseCommandArgs(['--trace-json', '--bc', 'examples/hello.mulda']);
  assert.strictEqual(muldaJson.options.trace, true);
  assert.strictEqual(muldaJson.options.traceFormat, 'json');
  assert.strictEqual(muldaJson.options.bytecode, true);
}

function testTraceEventsPresentInBothBackends() {
  const source = ['Hokna', 'dej x = 1', 'x = x + 1', 'vyblij x'].join('\n');
  const { js, bytecode } = compileMulda(source);

  const jsTrace = [];
  vm.runInNewContext(js, {
    __muldaTraceHook: (event) => jsTrace.push(event),
    console: { log: () => {} }
  });
  assert(jsTrace.some((event) => event.op === 'DECLARE'));
  assert(jsTrace.some((event) => event.op === 'ASSIGN'));
  assert(jsTrace.some((event) => event.op === 'PRINT_EXPR'));
  assert(jsTrace.some((event) => event.op === 'DECLARE' && event.detail === 'x=1'));
  assert(jsTrace.some((event) => event.op === 'ASSIGN' && event.detail === 'x=2'));

  const vmTrace = [];
  runBytecodeObject(bytecode, {
    stdout: () => {},
    trace: (event) => vmTrace.push(event)
  });
  assert(vmTrace.some((event) => event.op === 'DECLARE'));
  assert(vmTrace.some((event) => event.op === 'ASSIGN'));
  assert(vmTrace.some((event) => event.op === 'PRINT_EXPR'));
  assert(vmTrace.some((event) => event.op === 'DECLARE' && event.detail === 'x=1'));
  assert(vmTrace.some((event) => event.op === 'ASSIGN' && event.detail === 'x=2'));
}

function testAssignUnknownVariableThrowsInVm() {
  const { bytecode } = compileMulda(['Hokna', 'x = 1'].join('\n'));
  assert.throws(
    () => runBytecodeObject(bytecode, { stdout: () => {} }),
    /Assignment failed: variable "x" is not declared/
  );
}

testVariablesAndPrint();
testAssignmentStatementParsingAndTranspile();
testControlFlowBlocks();
testBooleanTokensAndTypeAnnotation();
testFunctionDeclarationAndReturn();
testDeprecatedAliasesStillWork();
testStartKeywordRequiredAndUnique();
testUnexpectedKonecError();
testAssignmentValidationErrors();
testEqualityExpressionsAreNotParsedAsAssignments();
testBytecodeVmRunner();
testRuntimeArgParsers();
testTraceEventsPresentInBothBackends();
testAssignUnknownVariableThrowsInVm();
console.log('tests passed');
