#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function transpileHantec(source) {
  const lines = source.split(/\r?\n/);
  const out = [
    '// generated by hantec transpiler v0.1',
    '"use strict";',
    ''
  ];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;

    if (line.startsWith('rekni ')) {
      const text = line.slice('rekni '.length).trim();
      out.push(`console.log(${JSON.stringify(text)});`);
      continue;
    }

    if (line.startsWith('spocitej ')) {
      const expr = line.slice('spocitej '.length).trim();
      out.push(`console.log(${expr});`);
      continue;
    }

    throw new Error(`Unsupported syntax: "${line}"`);
  }

  return out.join('\n');
}

function emitBytecodePlaceholder(jsCode) {
  return {
    version: '0.1',
    target: 'node',
    note: 'bytecode backend placeholder',
    bytes: Buffer.from(jsCode, 'utf8').length
  };
}

function main() {
  const [, , inputFile, outputFile] = process.argv;
  if (!inputFile || !outputFile) {
    console.error('Usage: node compiler/src/transpile.js <input.hantec> <output.js>');
    process.exit(1);
  }

  const inputPath = path.resolve(inputFile);
  const outputPath = path.resolve(outputFile);
  const source = fs.readFileSync(inputPath, 'utf8');
  const js = transpileHantec(source);

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, js, 'utf8');

  const bytecodePath = outputPath.replace(/\.js$/, '.bytecode.json');
  fs.writeFileSync(bytecodePath, JSON.stringify(emitBytecodePlaceholder(js), null, 2));

  console.log(`Transpiled ${inputFile} -> ${outputFile}`);
  console.log(`Bytecode placeholder -> ${path.relative(process.cwd(), bytecodePath)}`);
}

if (require.main === module) {
  main();
}

module.exports = { transpileHantec, emitBytecodePlaceholder };
