#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function syntaxError(message, line, column = 1) {
  const err = new Error(`${message} (line ${line}, col ${column})`);
  err.line = line;
  err.column = column;
  return err;
}

function parseProgram(source) {
  const lines = source.split(/\r?\n/);
  const ast = [];

  for (let i = 0; i < lines.length; i += 1) {
    const lineNo = i + 1;
    const raw = lines[i];
    const trimmed = raw.trim();

    if (!trimmed || trimmed.startsWith('#')) continue;

    if (trimmed.startsWith('dej ')) {
      const rest = trimmed.slice('dej '.length).trim();
      const eq = rest.indexOf('=');
      if (eq === -1) {
        throw syntaxError('Expected "=" in variable declaration', lineNo);
      }

      const name = rest.slice(0, eq).trim();
      const expr = rest.slice(eq + 1).trim();

      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
        throw syntaxError(`Invalid variable name "${name}"`, lineNo);
      }
      if (!expr) {
        throw syntaxError('Variable declaration requires expression after "="', lineNo);
      }

      ast.push({ type: 'declare', name, expr, line: lineNo });
      continue;
    }

    if (trimmed.startsWith('rekni ')) {
      const text = trimmed.slice('rekni '.length).trim();
      if (!text) {
        throw syntaxError('rekni requires text', lineNo);
      }
      ast.push({ type: 'printText', text, line: lineNo });
      continue;
    }

    if (trimmed.startsWith('spocitej ')) {
      const expr = trimmed.slice('spocitej '.length).trim();
      if (!expr) {
        throw syntaxError('spocitej requires an expression', lineNo);
      }
      ast.push({ type: 'printExpr', expr, line: lineNo });
      continue;
    }

    throw syntaxError(`Unsupported syntax: "${trimmed}"`, lineNo);
  }

  return ast;
}

function generateJs(ast) {
  const out = [
    '// generated by hantec transpiler v0.2',
    '"use strict";',
    ''
  ];

  for (const node of ast) {
    if (node.type === 'declare') {
      out.push(`const ${node.name} = (${node.expr});`);
    } else if (node.type === 'printText') {
      out.push(`console.log(${JSON.stringify(node.text)});`);
    } else if (node.type === 'printExpr') {
      out.push(`console.log(${node.expr});`);
    }
  }

  return out.join('\n');
}

function transpileHantec(source) {
  const ast = parseProgram(source);
  return generateJs(ast);
}

function emitBytecodePlaceholder(jsCode) {
  return {
    version: '0.2',
    target: 'node',
    note: 'bytecode backend placeholder',
    bytes: Buffer.from(jsCode, 'utf8').length
  };
}

function main() {
  const [, , inputFile, outputFile] = process.argv;
  if (!inputFile || !outputFile) {
    console.error('Usage: node compiler/src/transpile.js <input.hantec> <output.js>');
    process.exit(1);
  }

  const inputPath = path.resolve(inputFile);
  const outputPath = path.resolve(outputFile);

  try {
    const source = fs.readFileSync(inputPath, 'utf8');
    const js = transpileHantec(source);

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, js, 'utf8');

    const bytecodePath = outputPath.replace(/\.js$/, '.bytecode.json');
    fs.writeFileSync(bytecodePath, JSON.stringify(emitBytecodePlaceholder(js), null, 2));

    console.log(`Transpiled ${inputFile} -> ${outputFile}`);
    console.log(`Bytecode placeholder -> ${path.relative(process.cwd(), bytecodePath)}`);
  } catch (err) {
    console.error(err.message || String(err));
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  syntaxError,
  parseProgram,
  generateJs,
  transpileHantec,
  emitBytecodePlaceholder
};
